name: xlo
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation: ^0.17.9
  rxdart: ^0.23.1
  brasil_fields: ^0.0.7+2
  image_picker: 0.6.7+7
  cached_network_image: ^2.0.0-rc
  parse_server_sdk: ^1.0.25
  geolocator: ^5.3.0
  url_launcher: ^5.4.2
  carousel_pro: ^1.0.0
  path_provider: ^1.6.5
  flutter_image_compress: ^0.6.5+1
  transparent_image: ^1.0.0
  flutter_masked_text: ^0.8.0
  provider: ^4.0.4
  shared_preferences: ^0.5.6+3
  connectivity: ^0.4.8+2
  onesignal_flutter: ^2.3.4
  image_cropper: ^1.2.1
  location_permissions: ^2.0.5
  dio: ^3.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - images/


